#!/usr/bin/python

# This is a simple wrapper intended for use with the --diff3-cmd argument of
# 'svn merge' (or indeed 'svnmerge') and uses gvimiff as the diffing tool.
# It makes Vim name the buffers according to what Subversion passes in
# as the names for the files. This may look like
#   file.c	(.../trunk/file.c)	(revision 72)
# Note the tabs and slashes. Both confuse Vim, so we replace whitespace by
# regular spaces and slashes by backslashes.
# Also, we ensure that we get nice syntax highlighting in Vim by creating
# symlinks with appropriate extensions to the temp files we are given.
# The easiest way to use this script is by setting
#   diff-cmd = svndiff_helper
# in section [helpers] in your ~/.subversion/config.

import sys, re, subprocess, os, os.path

n1, n2, n3 = sys.argv[4], sys.argv[6], sys.argv[8]
f1, f2, f3 = sys.argv[9], sys.argv[10], sys.argv[11]

def lntemp(f, n):
    fn = n.split('\t')[0]
    ext = os.path.splitext(fn)[1]
    if ext not in ("", os.path.splitext(f)[1]):
        tmpfn = f + ext
        os.symlink(os.path.basename(f), tmpfn)
        return tmpfn
    else: return f

lf1 = lntemp(f1, n1)
lf2 = lntemp(f2, n2)
lf3 = lntemp(f3, n3)

def sanitise(n):
    n = re.sub(r'\s+', r'\ ', n)
    n = re.sub(r'/',   r'\\\\', n)
    return n

vim_rc = subprocess.call(['vim', '-dfgR',
    '--cmd', "au BufReadPost " + lf2 + " silent f " + sanitise(n2),
    '--cmd', "au BufReadPost " + lf1 + " silent f " + sanitise(n1),
    '--cmd', "au BufReadPost " + lf3 + " silent f " + sanitise(n3),
    lf2, lf1, lf3])

if lf1 != f1: os.remove(lf1)
if lf2 != f2: os.remove(lf2)
if lf3 != f3: os.remove(lf3)

sys.exit(vim_rc)

